### ISSUE TITLE
Text-Tabs-Wrap: strict / warnings patches unwelcome

### ISSUE THREAD

**Issue by atoomic** [toddr/perl-modernization#16]
not really cooperative author, in a middle of a long term refactor... not accepting patches...

- add gh ci https://github.com/muir/Text-Tabs-Wrap/pull/7 
- Use INST_LIB instead of INST_LIBDIR https://github.com/muir/Text-Tabs-Wrap/pull/9 
- enforce strict/warnings https://github.com/muir/Text-Tabs-Wrap/pull/10/files

**Comment by toddr** [comment]
I'm 99% certain this is not the right repo. all tickets have been closed/rejected.

**Comment by ap** [comment]
> all tickets have been closed/rejected.

FWIW I had not intended to do that. GitHub just decided to take my force-push to `master` to mean that I also wanted it to close all the PRs on my behalf… which I absolutely did not. All I wanted was to redirect people to the correct repo, since I was getting patches for things I had already fixed there.

**Comment by toddr** [comment]
Understood. all good!
